"""Shared helpers for LH017: paths, CSV files, the read log, git, names and LH008's pin rules.

Copied from studies/LH015/scripts/common.py (which carried LH008's pinned-file rules, candidate and versions_in, from
studies/LH010/scripts/collect.py unchanged), with this study's paths; LH015's recipe helpers are left out.
"""
import csv
import datetime
import json
import os
import re
import subprocess
import threading

from packaging.version import Version, InvalidVersion

HERE = os.path.dirname(os.path.abspath(__file__))
STUDY = os.path.dirname(HERE)
DATA = os.environ.get('LH017_DATA', os.path.join(STUDY, 'data'))
SCRATCH = os.environ.get('LH017_SCRATCH',
                         '/tmp/claude-0/-home-user-lighthouse/e1ee9d00-0026-4aaf-b54b-89c099c5b5a7/scratchpad/lh017')
REPOS = os.path.join(SCRATCH, 'repos')
csv.field_size_limit(1 << 26)


def now():
    return datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')


def read_csv(name, base=None):
    with open(os.path.join(base or DATA, name), newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))


def write_csv(name, rows, fields, base=None):
    os.makedirs(base or DATA, exist_ok=True)
    with open(os.path.join(base or DATA, name), 'w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=fields, lineterminator='\n')
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, '') for k in fields})


LOG_FIELDS = ['read_utc', 'source', 'repo', 'commit', 'path', 'method', 'endpoint', 'status', 'bytes', 'seconds', 'note']
_LOCK = threading.Lock()


def log(**row):
    """Append one row to data/read_log.csv (every clone, retry, file read and web request)."""
    p = os.path.join(DATA, 'read_log.csv')
    with _LOCK:
        new = not os.path.exists(p)
        with open(p, 'a', newline='', encoding='utf-8') as f:
            w = csv.DictWriter(f, fieldnames=LOG_FIELDS, lineterminator='\n')
            if new:
                w.writeheader()
            w.writerow({k: row.get(k, '') for k in LOG_FIELDS})


def git(args, cwd=None, check=True, timeout=900):
    """git without credentials or prompts (anonymous HTTPS through the environment's proxy), as LH010 ran it."""
    p = subprocess.run(['git', '-c', 'credential.helper=', '-c', 'core.askPass=true'] + args, cwd=cwd,
                       capture_output=True, text=True, timeout=timeout, env={**os.environ, 'GIT_TERMINAL_PROMPT': '0'},
                       errors='replace')
    if check and p.returncode != 0:
        raise RuntimeError(f'git {" ".join(args[:2])}: {p.stderr[:300]}')
    return p.stdout


def repo_dir(repo):
    return os.path.join(REPOS, repo.replace('/', '__'))


def du(path):
    p = subprocess.run(['du', '-sb', path], capture_output=True, text=True)
    return int(p.stdout.split()[0]) if p.returncode == 0 and p.stdout else 0


def norm(n):
    """PEP 503 normalised name."""
    return re.sub(r'[-_.]+', '-', n).lower()


def V(s):
    try:
        return Version(s)
    except (InvalidVersion, TypeError):
        return None


def instant(s):
    """An ISO 8601 time as a UTC instant (committer times are compared as instants, not strings)."""
    s = s.strip().replace('Z', '+00:00')
    return datetime.datetime.fromisoformat(s).astimezone(datetime.timezone.utc)


# ------------------------------------------------------------------ LH008's pinned-file rules (via LH010)

SKIP = re.compile(r'(?i)(^|/)(tests?|testing|test_[^/]*|[^/]*_tests?|examples?|[^/]*_examples?|docs?)/'
                  r'|(^|/)(\.venv|venv|site-packages|vendor|node_modules|third_party)/')


def candidate(path):
    if path.count('/') > 3 or SKIP.search(path):
        return None
    return kind_of(path)


def kind_of(path):
    """LH008's file kind by name alone, at any depth (class 4 reads files beyond LH008's depth and directories)."""
    b = path.rsplit('/', 1)[-1]
    if b in ('uv.lock', 'poetry.lock', 'pdm.lock', 'Pipfile.lock'):
        return 'lockfile'
    if b in ('pyproject.toml', 'setup.py', 'setup.cfg', 'Pipfile'):
        return 'manifest'
    if re.search(r'(?i)requirements[^/]*\.txt$', b) or (re.search(r'(?i)(^|/)requirements/', path) and b.endswith('.txt')):
        return 'requirements'
    if re.fullmatch(r'(?i)pylock(\.[^/]+)?\.toml', b):
        return 'lockfile'
    return None


GENERATED = re.compile(r'(?i)autogenerated by pip-compile|uv pip compile|this file was autogenerated by uv|uv export|pdm export'
                       r'|poetry export|generated by pip-compile')


def lib_re(lib):
    return re.escape(norm(lib)).replace(r'\-', '[-_.]')


def versions_in(path, text, lib, kind):
    """(class, [versions]) the file holds for the library: 'lockfile' or 'exact pin', or (None, []). LH008's rule;
    pylock.toml is read like uv.lock ([[packages]] tables with name and version), the one addition class 4 names."""
    n = lib_re(lib)
    b = path.rsplit('/', 1)[-1]
    if kind == 'lockfile' and b != 'Pipfile.lock':
        vs = []
        for blk in re.split(r'\n\[\[packages?\]\]', '\n' + text):
            m = re.search(r'^name\s*=\s*"([^"]+)"', blk, re.M)
            if m and norm(m.group(1)) == norm(lib):
                mv = re.search(r'^version\s*=\s*"([^"]+)"', blk, re.M)
                if mv:
                    vs.append(mv.group(1))
        return ('lockfile', vs) if vs else (None, [])
    if b == 'Pipfile.lock':
        try:
            j = json.loads(text)
        except Exception:
            return (None, [])
        vs = [x.get('version', '').lstrip('=') for sec in ('default', 'develop') for k, x in (j.get(sec) or {}).items()
              if norm(k) == norm(lib) and isinstance(x, dict) and x.get('version', '').startswith('==')]
        return ('lockfile', vs) if vs else (None, [])
    pat = re.compile(r'(?i)(?<![\w.\-/])' + n + r'(\[[^\]]*\])?\s*===?\s*([0-9][^\s"\',;#\\)\]*]*)(?![*\w.])')
    vs = [m.group(2) for m in pat.finditer(text)]
    if b == 'pyproject.toml' or b == 'Pipfile':
        for m in re.finditer(r'(?im)^\s*"?' + n + r'"?\s*=\s*(?:\{[^}\n]*version\s*=\s*)?"(?:==)?([0-9][0-9A-Za-z.+!-]*)"', text):
            vs.append(m.group(1))
    vs = [v for v in vs if V(v)]
    if not vs:
        return (None, [])
    if kind == 'requirements' and GENERATED.search(text[:3000]):
        return ('lockfile', vs)
    return ('exact pin', vs)


def names_lib(text, lib):
    """True if the text names the library as a whole word (any spelling PEP 503 treats as the same)."""
    return re.search(r'(?i)(?<![\w.\-/])' + lib_re(lib) + r'(?![\w\-])', text or '') is not None
