"""LH015 phase 2: clone, find each snapshot, and read the recipes and the files they name.

python3 collect.py clone   one blobless anonymous clone per repository, in frame order, a few at a time; a failed clone
                           is tried once more at least 60 seconds later; each attempt is logged in data/read_log.csv
python3 collect.py read    verify each pair's snapshot (commit resolves, unambiguous, committer time equal to snapshot_time
                           as an instant); list the snapshot and head trees; read recipes, ignore files, compose files,
                           workflows (where a recipe exists), and the scripts, Makefiles, requirements files and manifests
                           that install steps call or name; write data/pairs_read.csv, recipes.csv, recipe_lines.csv,
                           aux_lines.csv and tree_paths.csv
python3 collect.py clean   delete the clones

Ceilings (brief): 664 clone attempts; 6 GB of clones on disk at any time (checked before each clone, stopping at 5.5 GB
to leave room for clones in flight) and 8 GB in all; 15,000 git show reads; two hours.
"""
import concurrent.futures as cf
import os
import shutil
import sys
import threading
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import *  # noqa: E402,F401

WORKERS = 8
CLONE_TIMEOUT = 900
DISK_STOP = 5.5e9
TOTAL_STOP = 7.5e9
_T = threading.Lock()
TALLY = {'disk': 0, 'attempts': 0}


def frame():
    return read_csv('frame.csv')


def repos_in_order():
    seen, out = set(), []
    for r in frame():
        if r['repo'] not in seen:
            seen.add(r['repo'])
            out.append(r['repo'])
    return out


def clone(repo, attempt):
    d = repo_dir(repo)
    if os.path.exists(os.path.join(d, 'HEAD')):
        return 'already cloned'
    with _T:
        if TALLY['disk'] > DISK_STOP or TALLY['disk'] > TOTAL_STOP or TALLY['attempts'] >= 664:
            st = 'not cloned: ceiling'
            log(read_utc=now(), source='git over HTTPS', repo=repo, method='git clone --filter=blob:none --no-checkout',
                endpoint='https://' + repo + '.git', status=st, note=f'attempt {attempt}')
            return st
        TALLY['attempts'] += 1
    t0, t = time.time(), now()
    try:
        git(['clone', '-q', '--filter=blob:none', '--no-checkout', 'https://' + repo + '.git', d], timeout=CLONE_TIMEOUT)
        st = 'cloned'
    except Exception as ex:
        st = 'failed: ' + str(ex)[:200].replace('\n', ' ')
        shutil.rmtree(d, ignore_errors=True)
    b = du(d) if st == 'cloned' else 0
    with _T:
        TALLY['disk'] += b
    log(read_utc=t, source='git over HTTPS', repo=repo, method='git clone --filter=blob:none --no-checkout',
        endpoint='https://' + repo + '.git', status=st, bytes=b or '', seconds=round(time.time() - t0, 1),
        note=f'attempt {attempt}')
    return st


def do_clone():
    os.makedirs(REPOS, exist_ok=True)
    only = set(sys.argv[2].split(',')) if len(sys.argv) > 2 else None
    repos = [r for r in repos_in_order() if not only or r in only]
    TALLY['attempts'] = sum(1 for r in read_csv('read_log.csv') if r['method'].startswith('git clone')) if only else 0
    TALLY['disk'] = du(REPOS)
    t0 = time.time()
    with cf.ThreadPoolExecutor(WORKERS) as ex:
        res = dict(zip(repos, ex.map(lambda r: clone(r, 1), repos)))
    failed = [r for r, s in res.items() if s.startswith('failed')]
    print(f'first pass: {sum(s == "cloned" for s in res.values())} cloned, {len(failed)} failed, '
          f'{round(time.time() - t0)} s, {TALLY["disk"] / 1e9:.2f} GB', flush=True)
    if failed:
        time.sleep(65)
        with cf.ThreadPoolExecutor(3) as ex:
            res2 = dict(zip(failed, ex.map(lambda r: clone(r, 2), failed)))
        print(f'retries: {sum(s == "cloned" for s in res2.values())} cloned of {len(failed)}', flush=True)
    print(f'attempts {TALLY["attempts"]}, on disk {TALLY["disk"] / 1e9:.2f} GB, {round(time.time() - t0)} s', flush=True)


# ================================================================ reading

import hashlib  # noqa: E402
import json  # noqa: E402
import re  # noqa: E402
import shlex  # noqa: E402
import subprocess  # noqa: E402
import yaml  # noqa: E402
import classify as C  # noqa: E402

CACHE = os.path.join(SCRATCH, 'cache')
READS = {'show': 0}
KEEP = re.compile(r'(?i)(^\s*-[rce]\b|^\s*--(requirement|constraint|editable)|^\s*\.|name\s*=|dynamic|file\s*[=:]|requirements|'
                  r'open\(|\bpip3?\b|\buv\b|poetry|pipenv|\bpdm\b|conda|mamba|setup\.py|pipx|\bmake\b|^\s*cd\s|\bcd\s|export\s|'
                  r'source\s|activate|\.sh\b|install|sync|^[A-Za-z0-9_.%/-]+\s*:(?!=)|autogenerated|generated by)')


def show(repo, commit, path):
    """git show <commit>:<path>, cached in the scratchpad; each first read is logged."""
    d = repo_dir(repo)
    cp = os.path.join(CACHE, repo.replace('/', '__'), commit, hashlib.sha1(path.encode()).hexdigest())
    if os.path.exists(cp):
        with open(cp, encoding='utf-8', errors='replace') as f:
            t = f.read()
        return None if t == '\x00UNREADABLE' else t
    t0, when = time.time(), now()
    try:
        txt = git(['show', f'{commit}:{path}'], cwd=d, timeout=300)
        st = 'ok'
    except Exception as ex:
        txt, st = None, 'failed: ' + str(ex)[:120].replace('\n', ' ')
    with _T:
        READS['show'] += 1
    log(read_utc=when, source='git over HTTPS (blob fetched on demand)', repo=repo, commit=commit, path=path, method='git show',
        status=st, bytes=len(txt.encode()) if txt is not None else '', seconds=round(time.time() - t0, 2))
    os.makedirs(os.path.dirname(cp), exist_ok=True)
    with open(cp, 'w', encoding='utf-8') as f:
        f.write(txt if txt is not None else '\x00UNREADABLE')
    return txt


def relevant(text, libs, path=''):
    b = path.rsplit('/', 1)[-1]
    if b == 'Pipfile.lock':
        try:
            j = json.loads(text)
            keep = {sec: {k: {'version': v.get('version', '')} for k, v in (j.get(sec) or {}).items()
                          if isinstance(v, dict) and any(norm(k) == norm(L) for L in libs)} for sec in ('default', 'develop')}
            return [json.dumps(keep, sort_keys=True)[:400]]
        except Exception:
            return []
    if b in ('uv.lock', 'poetry.lock', 'pdm.lock') or re.fullmatch(r'pylock(\.[^/]+)?\.toml', b):
        out = []
        for blk in re.split(r'\n\[\[packages?\]\]', '\n' + text):
            m = re.search(r'^name\s*=\s*"([^"]+)"', blk, re.M)
            mv = re.search(r'^version\s*=\s*"([^"]+)"', blk, re.M)
            if m and mv and any(norm(m.group(1)) == norm(L) for L in libs):
                out += ['[[package]]', m.group(0), mv.group(0)]
        return out
    out = []
    for t in text.replace('\r\n', '\n').split('\n'):
        if KEEP.search(t) or any(names_lib(t, L) for L in libs):
            out.append(t[:400])
    return out[:1500]


class LiveTree:
    """The tree at one commit, recording every query and read for classify.py's offline replay."""

    def __init__(self, repo, commit, files, libs):
        self.repo, self.commit, self.files, self.libs = repo, commit, files, libs
        self.dirs = set()
        for f in files:
            parts = f.split('/')[:-1]
            for k in range(1, len(parts) + 1):
                self.dirs.add('/'.join(parts[:k]))
        self.q, self.aux = {}, {}

    def exists(self, p):
        r = p == '' or p in self.files or p in self.dirs
        self.q[('exists', p)] = 'yes' if r else 'no'
        return r

    def isdir(self, p):
        r = p == '' or p in self.dirs
        self.q[('isdir', p)] = 'yes' if r else 'no'
        return r

    def glob(self, ctx, pat):
        full = C.J(ctx, pat)
        rx = re.compile(C.glob_re(full))
        m = sorted(f for f in self.files if rx.match(f))[:200]
        self.q[('glob', full)] = '|'.join(m)
        return m

    def lines(self, p, kind=None, lib=None):
        if p in self.aux:
            st, ls = self.aux[p]
            return ls if st == 'read' else None
        if p not in self.files:
            self.aux[p] = ('unreadable', [])
            return None
        txt = show(self.repo, self.commit, p)
        if txt is None:
            self.aux[p] = ('unreadable', [])
            return None
        ls = relevant(txt, self.libs, p)
        self.aux[p] = ('read', ls)
        return ls

    def read_all(self, p, kind):
        """A file stored whole in aux_lines (ignore files), or its raw text for parsing (compose, workflows)."""
        txt = show(self.repo, self.commit, p) if p in self.files else None
        return txt


def sources_of(stages, path, env0):
    """Local COPY, ADD and bind-mount sources in the final path, for the context rule (2)."""
    out = []
    for i in path:
        env = dict(env0)
        for ins in stages[i]['ins']:
            if ins['op'] == 'ARG':
                for k, v in C.parse_arg(ins['rest']):
                    if v is not None:
                        env[k] = C.subst(v, env)
            elif ins['op'] == 'ENV':
                for k, v in C.parse_env(C.subst(ins['rest'], env)):
                    env[k] = v
            elif ins['op'] in ('COPY', 'ADD'):
                flags, excl, srcs, dest = C.copy_parts(C.subst(ins['rest'], env))
                if 'from' not in flags:
                    out += [x for x in srcs if not re.match(r'^[a-z]+://', x)]
            elif ins['op'] == 'RUN':
                for m in C.run_parts(ins['rest'])[0]:
                    if m.get('type', 'bind') == 'bind' and not m.get('from') and (m.get('target') or m.get('dst')):
                        out.append(C.subst(m.get('source') or m.get('src') or '.', env))
    return [x for x in out if '$' not in x and C.UNK not in x and '{{' not in x]


def exists_under(tree, base, src):
    rel = C.posixpath.normpath(src.lstrip('/'))
    if rel in ('.', ''):
        return True
    if rel.startswith('..'):
        return False
    if re.search(r'[*?\[]', rel):
        rx = re.compile(C.glob_re(C.J(base, rel)))
        return any(rx.match(f) for f in tree.files) or any(rx.match(d) for d in tree.dirs)
    p = C.J(base, rel)
    return p in tree.files or p in tree.dirs


def ancestors(d):
    out = [d]
    while d:
        d = parent(d)
        out.append(d)
    return out


def compose_builds(tree, repo, commit, composes):
    """Build stanzas of the compose files: (compose path, service, context, dockerfile path, target, args, inline text)."""
    out, notes = [], []
    for cpath in composes:
        txt = tree.read_all(cpath, 'compose')
        if txt is None:
            notes.append(f'compose unreadable {cpath}')
            out.append({'compose': cpath, 'unreadable': True})
            continue
        try:
            doc = yaml.safe_load(txt) or {}
        except Exception:
            notes.append(f'compose not parsed {cpath}')
            continue
        if not isinstance(doc, dict):
            continue
        svcs = doc.get('services') if isinstance(doc.get('services'), dict) else \
            ({k: v for k, v in doc.items() if isinstance(v, dict) and 'build' in v} if 'services' not in doc else {})
        for name, sv in (svcs or {}).items():
            if not isinstance(sv, dict) or 'build' not in sv:
                continue
            b = sv['build']
            b = {'context': b} if isinstance(b, str) else (b if isinstance(b, dict) else {})
            ctx = str(b.get('context', '.'))
            if re.match(r'^[a-z]+://|^git@', ctx) or '$' in ctx:
                continue
            ctxp = C.J(parent(cpath), ctx)
            args = b.get('args') or {}
            if isinstance(args, list):
                args = dict(x.split('=', 1) for x in args if isinstance(x, str) and '=' in x)
            args = {str(k): str(v) for k, v in args.items() if v is not None and '$' not in str(v)}
            ent = {'compose': cpath, 'service': str(name), 'context': ctxp, 'target': str(b.get('target') or ''), 'args': args}
            if b.get('dockerfile_inline'):
                ent['inline'] = str(b['dockerfile_inline'])
                ent['dockerfile'] = cpath + '#' + str(name)
            else:
                df = str(b.get('dockerfile') or 'Dockerfile')
                if '$' in df:
                    continue
                ent['dockerfile'] = C.J(ctxp, df)
            out.append(ent)
        keep = [t[:400] for t in txt.split('\n') if re.search(r'build|context|dockerfile|target|args', t)]
        facts = ['LH015-build ' + json.dumps({k: v for k, v in e.items() if k != 'inline'}, sort_keys=True)[:390]
                 for e in out if e.get('compose') == cpath]
        if facts:
            tree.aux[cpath] = ('read', keep[:300] + facts)
    return out, notes


BUILD_VALUED = {'-f', '--file', '-t', '--tag', '--target', '--build-arg', '--platform', '--label', '--cache-from', '--cache-to',
                '-o', '--output', '--secret', '--ssh', '--progress', '--network', '--iidfile', '--metadata-file', '--builder',
                '--build-context', '--attest', '--provenance', '--sbom', '--annotation', '--add-host', '--shm-size', '--ulimit',
                '--dockerfile', '--context', '--destination', '--memory', '-m', '--cpu-quota', '--isolation', '--pull'}


def workflow_builds(tree, repo, commit, wfs):
    out, notes = [], []
    for w in wfs:
        txt = tree.read_all(w, 'workflow')
        if txt is None:
            notes.append(f'workflow unreadable {w}')
            continue
        try:
            doc = yaml.safe_load(txt) or {}
        except Exception:
            doc = {}
        steps = []
        if isinstance(doc, dict):
            for jn, job in (doc.get('jobs') or {}).items() if isinstance(doc.get('jobs'), dict) else []:
                if not isinstance(job, dict):
                    continue
                jwd = (((job.get('defaults') or {}).get('run') or {}).get('working-directory')) if isinstance(job.get('defaults'), dict) else None
                for stp in job.get('steps') or []:
                    if isinstance(stp, dict):
                        steps.append((stp, stp.get('working-directory') or jwd or ''))
        for stp, wd in steps:
            u = str(stp.get('uses') or '')
            if u.startswith('docker/build-push-action'):
                wi = stp.get('with') or {}
                ctx = str(wi.get('context') or '.')
                f = str(wi.get('file') or '')
                if '${{' in ctx + f:
                    continue
                ctxp = C.J(ctx)
                args = {}
                for ln in str(wi.get('build-args') or '').splitlines():
                    if '=' in ln and '$' not in ln:
                        k, v = ln.strip().split('=', 1)
                        args[k] = v
                out.append({'workflow': w, 'context': ctxp, 'dockerfile': C.J(f) if f else C.J(ctxp, 'Dockerfile'),
                            'target': str(wi.get('target') or ''), 'args': args})
        texts = [(str(s.get('run')), wd) for s, wd in steps if s.get('run')]
        if w.endswith('.gitlab-ci.yml') and isinstance(doc, dict):
            for job in doc.values():
                if isinstance(job, dict):
                    for k in ('script', 'before_script'):
                        v = job.get(k)
                        texts += [(str(x), '') for x in (v if isinstance(v, list) else [v] if v else [])]
        for t, wd in texts:
            t = t.replace('\\\n', ' ')
            for ln in t.split('\n'):
                m = re.search(r'(docker(?:\s+buildx)?\s+build|podman\s+build|buildah\s+(?:bud|build)|/kaniko/executor)\s(.*)', ln)
                if not m or '${{' in ln:
                    continue
                try:
                    toks = shlex.split(m.group(2))
                except ValueError:
                    continue
                f, tgt, args, pos, i = '', '', {}, [], 0
                while i < len(toks):
                    a = toks[i]
                    k, eq, v = a.partition('=')
                    if k in BUILD_VALUED:
                        if not eq:
                            v = toks[i + 1] if i + 1 < len(toks) else ''
                            i += 1
                        if k in ('-f', '--file', '--dockerfile'):
                            f = v
                        elif k == '--target':
                            tgt = v
                        elif k == '--context':
                            pos.append(v)
                        elif k == '--build-arg' and '=' in v and '$' not in v:
                            args[v.split('=', 1)[0]] = v.split('=', 1)[1]
                    elif not a.startswith('-'):
                        if a in ('&&', '|', ';', '||'):
                            break
                        pos.append(a)
                    i += 1
                ctx = pos[-1] if pos else '.'
                if '$' in ctx + f or re.match(r'^[a-z]+://', ctx):
                    continue
                ctxp = C.J(wd, ctx)
                out.append({'workflow': w, 'context': ctxp, 'dockerfile': C.J(wd, f) if f else C.J(ctxp, 'Dockerfile'),
                            'target': tgt, 'args': args})
        facts = ['LH015-build ' + json.dumps(e, sort_keys=True)[:390] for e in out if e.get('workflow') == w]
        if facts:
            keep = [t[:400] for t in txt.split('\n') if re.search(
                r'docker|buildx|build-push-action|context:|file:|target|build-args|working-directory|kaniko|podman|buildah', t)]
            tree.aux[w] = ('read', keep[:300] + facts)
    return out, notes


def own_names(tree):
    s = set()
    for f in tree.files:
        b = f.rsplit('/', 1)[-1]
        if b in ('pyproject.toml', 'setup.py', 'setup.cfg') and '/' in f:
            s.add(norm(parent(f).rsplit('/', 1)[-1]))
    return s


def analyse_commit(repo, commit, files, pairs, role, fr_files):
    """Recipes, builds, contexts and classes at one commit, for the given pairs. Returns rows for the tables."""
    libs = sorted({p['library'] for p in pairs})
    tree = LiveTree(repo, commit, set(files), libs)
    res = {'recipes': [], 'lines': [], 'aux': [], 'q': [], 'pairinfo': {}}
    prim = [f for f in files if recipe_form(f) and not excluded(f)]
    nonprim = [f for f in files if recipe_form(f) and excluded(f)]
    others = [f for f in files if OTHER_DEFS.match(f.rsplit('/', 1)[-1]) and not excluded(f)]
    composes = sorted([f for f in files if COMPOSE.match(f.rsplit('/', 1)[-1]) and
                       not re.search(r'(^|/)(node_modules|vendor|site-packages|\.venv|venv|third_party)/', f)],
                      key=lambda x: (x.count('/'), x))[:40]
    cbuilds, notes = compose_builds(tree, repo, commit, composes)
    inline = [b for b in cbuilds if b.get('inline') and not excluded(b['compose'])]
    for f in nonprim:
        show(repo, commit, f)
    info = {'n_primary': len(prim) + len(inline), 'n_nonprimary': len(nonprim),
            'n_default_name': sum(1 for f in prim if recipe_form(f) == 'default'),
            'recipes': '|'.join(prim + [b['dockerfile'] for b in inline])[:1000],
            'nonprimary': '|'.join(nonprim)[:600], 'other_defs': '|'.join(others)[:300], 'compose_files': len(composes),
            'notes': '; '.join(notes)[:300]}
    if not prim and not inline:
        for p in pairs:
            res['pairinfo'][p['pair_id']] = info
        return res, tree
    wfs = [f for f in files if is_workflow(f)]
    wbuilds, wnotes = workflow_builds(tree, repo, commit, wfs)
    info['notes'] = '; '.join(notes + wnotes)[:300]
    info['workflows'] = len(wfs)
    ext_builds = [b for b in cbuilds + wbuilds if b.get('dockerfile')]
    own = own_names(tree)
    k = 0
    for rp in prim + [b['dockerfile'] for b in inline]:
        k += 1
        if '#' in rp:
            txt = next(b['inline'] for b in inline if b['dockerfile'] == rp)
        else:
            txt = show(repo, commit, rp)
        note = ''
        if txt is not None and not C.stages_of(C.parse_dockerfile(txt))[1] and txt.strip() and '\n' not in txt.strip():
            tp = C.posixpath.normpath(C.posixpath.join(parent(rp), txt.strip()))
            if tp in tree.files:
                txt, note = show(repo, commit, tp), f'symbolic link to {tp}, read at its target'
        tmpl = is_template(rp)
        base = {'commit': commit, 'role': role, 'path': rp, 'name_form': recipe_form(rp.split('#')[0]) or 'inline',
                'depth': rp.split('#')[0].count('/'), 'primary': 'yes', 'template': 'yes' if tmpl else 'no', 'note': note}
        if txt is None:
            for p in pairs:
                res['recipes'].append({**base, 'pair_id': p['pair_id'], 'build_id': f"{p['pair_id']}-{role[0]}{k}-0",
                                       'readable': 'unreadable'})
            continue
        instrs = C.parse_dockerfile(C.template_marks(txt) if tmpl else txt)
        g, stages = C.stages_of(instrs)
        refs = [b for b in ext_builds if b['dockerfile'] == rp]
        specs = []
        if refs:
            for b in refs:
                specs.append((b['context'], '', b['args'], 'compose' if 'compose' in b else 'workflow'))
                if b['target']:
                    specs.append((b['context'], b['target'], b['args'], 'compose' if 'compose' in b else 'workflow'))
        else:
            specs.append((None, '', {}, ''))
        seen, builds = set(), []
        for ctx, tgt, args, how in specs:
            key = (ctx, tgt, json.dumps(args, sort_keys=True))
            if key in seen:
                continue
            seen.add(key)
            builds.append((ctx, tgt, args, how))
        paths_used = set()
        for j, (ctx, tgt, args, how) in enumerate(builds):
            g2, st2 = C.stages_of(instrs, args)
            if not st2:
                path, cands = [], []
            else:
                ti = len(st2) - 1 if not tgt else C.stage_ref(st2, tgt, len(st2))
                path = C.final_path(st2, ti) if ti is not None else []
            paths_used |= set(path)
            cands = []
            if ctx is None:
                srcs = sources_of(st2, path, {**{k2: v for k2, v in g2.items() if v is not None}, **args})
                rdir = parent(rp.split('#')[0]) if '#' not in rp else parent(rp.split('#')[0])
                ctx_how = 'undetermined'
                for d in ancestors(rdir):
                    if all(exists_under(tree, d, s) for s in srcs):
                        ctx, ctx_how = d, ('recipe directory' if d == rdir else 'ancestor')
                        break
                if ctx is None:
                    cands = ancestors(rdir)
                    ctx = ''
            else:
                ctx_how = how
            beside = rp.split('#')[0] + '.dockerignore'
            ign = beside if beside in tree.files else C.J(ctx, '.dockerignore')
            for ip in ([ign] if ctx_how != 'undetermined' else [beside] + [C.J(c, '.dockerignore') for c in cands]):
                if ip in tree.files and ip not in tree.aux:
                    t = show(repo, commit, ip)
                    tree.aux[ip] = ('read', [x[:400] for x in t.split('\n')][:500]) if t is not None else ('unreadable', [])
            for p in pairs:
                T = [f['path'] for f in fr_files[p['pair_id']]]
                if role == 'head':
                    T = [t for t in T if t in tree.files]
                row = {**base, 'pair_id': p['pair_id'], 'build_id': f"{p['pair_id']}-{role[0]}{k}-{j}", 'readable': 'yes',
                       'stages': len(st2), 'final_path': ' '.join(map(str, path)), 'target': tgt, 'context': ctx,
                       'context_how': ctx_how, 'context_candidates': '|'.join(cands),
                       'ignore_file': ign if ign in tree.files else '', 'build_args': json.dumps(args, sort_keys=True),
                       'own_names': '|'.join(sorted(own)), 'T_paths': '|'.join(T)}
                res['recipes'].append(row)
                T_kind = {f['path']: f['pin_class'] for f in fr_files[p['pair_id']]}
                pinned = sorted({v for f in fr_files[p['pair_id']] for v in f['versions'].split(',') if v})
                owns = {p['package']} | own
                for c in (cands or [ctx]):
                    B = C.Ctx(instrs, tree, c, ign_lines(tree, rp, c),
                              T, T_kind, p['library'], pinned, owns, tgt or None, args, tmpl)
                    try:
                        C.classify_build(B)
                    except Exception as ex:
                        info['notes'] += f'; classify error {rp}: {str(ex)[:80]}'
        # recipe lines: every FROM, and the listed instructions of stages in a final path or that install
        inst_stage = {s['idx'] for s in stages if any(i['op'] == 'RUN' and re.search(r'pip|uv |poetry|pipenv|pdm|conda|mamba|setup\.py|make|\.sh', i['rest']) for i in s['ins'])}
        keep = paths_used | inst_stage
        pre = []
        for ins in instrs:
            if ins['op'] == 'FROM':
                break
            if ins['op'] == 'ARG':
                pre.append(ins)
        for ins in pre:
            res['lines'].append({'repo': repo, 'commit': commit, 'path': rp, 'stage': -1, 'n': ins['n'], 'op': 'ARG', 'part': 0,
                                 'text': ins['rest'][:400]})
        for s in stages:
            rows = [{'op': 'FROM', 'n': s['n'], 'rest': s['from_rest']}]
            for ins in (s['ins'] if s['idx'] in keep else []):
                if ins['op'] in ('ARG', 'ENV', 'WORKDIR', 'COPY', 'ADD', 'RUN', 'ENTRYPOINT', 'CMD'):
                    rows.append(ins)
            for ins in rows:
                t = ins['rest']
                for part in range(0, max(len(t), 1), 400):
                    res['lines'].append({'repo': repo, 'commit': commit, 'path': rp, 'stage': s['idx'], 'n': ins['n'],
                                         'op': ins['op'], 'part': part // 400, 'text': t[part:part + 400]})
    for p in pairs:
        res['pairinfo'][p['pair_id']] = info
    return res, tree


def ign_lines(tree, rp, ctx):
    beside = rp.split('#')[0] + '.dockerignore'
    for p in (beside, C.J(ctx, '.dockerignore')):
        if p in tree.files:
            if p not in tree.aux:
                t = show(tree.repo, tree.commit, p)
                tree.aux[p] = ('read', [x[:400] for x in t.split('\n')][:500]) if t is not None else ('unreadable', [])
            st, ls = tree.aux[p]
            return ls if st == 'read' else ['**']
    return []


def verify(d, pair):
    p = subprocess.run(['git', 'rev-parse', '--verify', '--quiet', pair['snapshot_commit'] + '^{commit}'], cwd=d,
                       capture_output=True, text=True)
    if p.returncode != 0:
        q = subprocess.run(['git', 'rev-parse', '--verify', pair['snapshot_commit'] + '^{commit}'], cwd=d,
                           capture_output=True, text=True)
        return None, 'snapshot absent: ' + ('ambiguous' if 'ambiguous' in q.stderr else 'does not resolve')
    full = p.stdout.strip()
    ct = git(['show', '-s', '--format=%cI', full], cwd=d).strip()
    if instant(ct) != instant(pair['snapshot_time']):
        return None, f'snapshot absent: committer time {ct} differs from {pair["snapshot_time"]}'
    return full, 'read'


def read_repo(repo, pairs, fr_files, head_at=None):
    d = repo_dir(repo)
    out = {'recipes': [], 'lines': [], 'aux': [], 'q': [], 'pairs': []}
    if not (os.path.exists(os.path.join(d, 'HEAD')) or os.path.exists(os.path.join(d, '.git', 'HEAD'))):
        for p in pairs:
            out['pairs'].append({'pair_id': p['pair_id'], 'status': 'not read: clone refused'})
        return out
    head = git(['rev-parse', 'HEAD'], cwd=d).strip() if not head_at else \
        git(['rev-parse', '--verify', head_at + '^{commit}'], cwd=d).strip()
    branch = subprocess.run(['git', 'symbolic-ref', '--short', 'HEAD'], cwd=d, capture_output=True, text=True).stdout.strip()
    todo = {}
    for p in pairs:
        full, st = verify(d, p)
        row = {'pair_id': p['pair_id'], 'status': st, 'head_commit': head[:12], 'head_branch': branch,
               'head_same_as_27sep': 'yes' if head.startswith(p['head_commit_27sep']) else 'no'}
        out['pairs'].append(row)
        if full:
            todo.setdefault(full[:12], []).append(p)
    trees = {}
    for c in list(todo) + [head[:12]]:
        if c in trees:
            continue
        try:
            t0 = time.time()
            ls = git(['ls-tree', '-r', '--name-only', c], cwd=d, timeout=600).split('\n')
            trees[c] = [x for x in ls if x]
            log(read_utc=now(), source='local clone', repo=repo, commit=c, method='git ls-tree -r --name-only',
                status='ok', bytes=len(trees[c]), seconds=round(time.time() - t0, 2), note='paths listed')
        except Exception as ex:
            trees[c] = None
            log(read_utc=now(), source='local clone', repo=repo, commit=c, method='git ls-tree -r --name-only',
                status='failed: ' + str(ex)[:100])
    info = {}
    for role, groups in (('snapshot', todo), ('head', {head[:12]: [p for ps in todo.values() for p in ps]} if todo else {})):
        for c, ps in groups.items():
            if trees.get(c) is None:
                for p in ps:
                    info[(p['pair_id'], role)] = {'status_' + role: 'tree unreadable'}
                continue
            res, tree = analyse_commit(repo, c, trees[c], ps, role, fr_files)
            out['recipes'] += res['recipes']
            out['lines'] += res['lines']
            for (kq, path), v in tree.q.items():
                out['q'].append({'repo': repo, 'commit': c, 'query': kq, 'path': path, 'result': v})
            for path, (st, ls) in tree.aux.items():
                out['aux'].append({'repo': repo, 'commit': c, 'path': path, 'line': 0, 'text': st})
                out['aux'] += [{'repo': repo, 'commit': c, 'path': path, 'line': i + 1, 'text': t} for i, t in enumerate(ls)]
            for pid, inf in res['pairinfo'].items():
                info[(pid, role)] = inf
    for row in out['pairs']:
        for role in ('snapshot', 'head'):
            inf = info.get((row['pair_id'], role))
            if inf:
                row.update({f'{role}_{k}': v for k, v in inf.items()})
    t_after = du(d)
    log(read_utc=now(), source='local clone', repo=repo, method='du -sb', endpoint=d, status='size after reads', bytes=t_after)
    return out


def do_read():
    fr = frame()
    fr_files = {}
    for r in read_csv('frame_files.csv'):
        fr_files.setdefault(r['pair_id'], []).append(r)
    by_repo = {}
    for r in fr:
        by_repo.setdefault(r['repo'], []).append(r)
    only = set(sys.argv[2].split(',')) if len(sys.argv) > 2 else None
    repos = [r for r in by_repo if not only or r in only]
    merge = bool(only) and os.environ.get('LH015_MERGE') == '1'
    heads = {}
    if merge:
        pid_repo = {r['pair_id']: r['repo'] for r in fr}
        for r in read_csv('pairs_read.csv'):
            heads.setdefault(pid_repo[r['pair_id']], r.get('head_commit', ''))
    t0 = time.time()
    allout = {'recipes': [], 'lines': [], 'aux': [], 'q': [], 'pairs': []}
    done = [0]

    def one(repo):
        try:
            o = read_repo(repo, by_repo[repo], fr_files, heads.get(repo))
        except Exception as ex:
            o = {'recipes': [], 'lines': [], 'aux': [], 'q': [],
                 'pairs': [{'pair_id': p['pair_id'], 'status': 'not read: error ' + str(ex)[:120]} for p in by_repo[repo]]}
        with _T:
            done[0] += 1
            if done[0] % 50 == 0:
                print(f'{done[0]} repositories, {READS["show"]} reads, {round(time.time() - t0)} s', flush=True)
        return o
    with cf.ThreadPoolExecutor(WORKERS) as ex:
        for o in ex.map(one, repos):
            for k in allout:
                allout[k] += o[k]
    order = {r['pair_id']: i for i, r in enumerate(fr)}
    allout['pairs'].sort(key=lambda r: order[r['pair_id']])
    pf = sorted({k for r in allout['pairs'] for k in r}, key=lambda k: (k != 'pair_id', k != 'status', k))
    suffix = '' if not only or merge else '_partial'
    if merge:
        pid_repo = {r['pair_id']: r['repo'] for r in fr}
        rorder = {r: i for i, r in enumerate(by_repo)}
        for name, key in (('pairs', lambda r: pid_repo[r['pair_id']]), ('recipes', lambda r: pid_repo[r['pair_id']]),
                          ('lines', lambda r: r['repo']), ('aux', lambda r: r['repo']), ('q', lambda r: r['repo'])):
            fname = {'pairs': 'pairs_read.csv', 'recipes': 'recipes.csv', 'lines': 'recipe_lines.csv', 'aux': 'aux_lines.csv',
                     'q': 'tree_paths.csv'}[name]
            old = [r for r in read_csv(fname) if key(r) not in only]
            allout[name] = sorted(old + allout[name], key=lambda r: rorder[key(r)])
        allout['pairs'].sort(key=lambda r: order[r['pair_id']])
        pf = sorted({k for r in allout['pairs'] for k in r}, key=lambda k: (k != 'pair_id', k != 'status', k))
    write_csv(f'pairs_read{suffix}.csv', allout['pairs'], pf)
    write_csv(f'recipes{suffix}.csv', allout['recipes'],
              ['build_id', 'pair_id', 'role', 'commit', 'path', 'name_form', 'depth', 'primary', 'template', 'readable', 'stages',
               'final_path', 'target', 'context', 'context_how', 'context_candidates', 'ignore_file', 'build_args',
               'own_names', 'T_paths', 'note'])
    write_csv(f'recipe_lines{suffix}.csv', allout['lines'], ['repo', 'commit', 'path', 'stage', 'n', 'op', 'part', 'text'])
    write_csv(f'aux_lines{suffix}.csv', allout['aux'], ['repo', 'commit', 'path', 'line', 'text'])
    write_csv(f'tree_paths{suffix}.csv', allout['q'], ['repo', 'commit', 'query', 'path', 'result'])
    print(f'read {len(repos)} repositories: {READS["show"]} new git show reads, {round(time.time() - t0)} s')


def do_pypi():
    """PyPI JSON for the builds classed 3 at snapshots: L's requirement in the release the recipe would install."""
    import urllib.request
    from packaging.requirements import Requirement
    from packaging.specifiers import SpecifierSet
    fr = {r['pair_id']: r for r in frame()}
    cache, rows, n = {}, [], [0]

    def get(url):
        if url in cache:
            return cache[url]
        if n[0] >= 150:
            return None
        n[0] += 1
        t0, when = time.time(), now()
        try:
            with urllib.request.urlopen(url, timeout=60) as r:
                body = r.read()
            st, j = 200, json.loads(body)
        except Exception as ex:
            st, j, body = getattr(ex, 'code', 'error'), None, b''
        log(read_utc=when, source='PyPI JSON API', endpoint=url, method='GET', status=st, bytes=len(body),
            seconds=round(time.time() - t0, 2))
        cache[url] = j
        return j
    for b in read_csv('recipe_classes.csv'):
        if str(b['class']) != '3' or b['role'] != 'snapshot':
            continue
        f = fr[b['pair_id']]
        snap_t = instant(f['snapshot_time'])
        for item in (b['own_spec'] or b['own_pkgs']).split():
            m = re.match(r'^([A-Za-z0-9._-]+)(.*)$', item)
            name, spec = norm(m.group(1)), m.group(2)
            j = get(f'https://pypi.org/pypi/{name}/json')
            row = {'build_id': b['build_id'], 'package': name, 'spec_named': spec}
            if not j:
                rows.append({**row, 'reading': 'not served'})
                continue
            exact = re.fullmatch(r'===?([^,*]+)', spec or '')
            if exact:
                ver, how = exact.group(1), 'version named'
            else:
                ok = []
                for v, fs in (j.get('releases') or {}).items():
                    vv = V(v)
                    ts = [instant(x['upload_time_iso_8601']) for x in fs if x.get('upload_time_iso_8601')]
                    if vv and not vv.is_prerelease and ts and min(ts) <= snap_t and (not spec or SpecifierSet(spec).contains(vv)):
                        ok.append(vv)
                ver, how = (str(max(ok)), 'newest non-pre-release at or before the snapshot') if ok else (None, 'none')
            if not ver:
                rows.append({**row, 'how': how, 'reading': 'no release'})
                continue
            jv = get(f'https://pypi.org/pypi/{name}/{ver}/json')
            req = ''
            for x in ((jv or {}).get('info') or {}).get('requires_dist') or []:
                try:
                    rq = Requirement(x)
                except Exception:
                    continue
                if norm(rq.name) == norm(f['library']):
                    req = str(rq.specifier) + (f'; {rq.marker}' if rq.marker else '')
            one = req and re.fullmatch(r'===?[^,*;]+', req.split(';')[0])
            rows.append({**row, 'version': ver, 'how': how, 'requires_L': req,
                         'reading': 'not served' if jv is None else 'published pin' if one else 'published range' if req else 'not listed'})
    write_csv('pypi.csv', rows, ['build_id', 'package', 'spec_named', 'version', 'how', 'requires_L', 'reading'])
    print(f'pypi: {len(rows)} rows, {n[0]} requests')


def do_clean():
    shutil.rmtree(REPOS, ignore_errors=True)
    log(read_utc=now(), source='local', method='rm -r', endpoint=REPOS, status='clones deleted')
    print('clones deleted')


if __name__ == '__main__':
    stage = sys.argv[1] if len(sys.argv) > 1 else ''
    if stage == 'clone':
        do_clone()
    elif stage == 'read':
        do_read()
    elif stage == 'pypi':
        do_pypi()
    elif stage == 'clean':
        do_clean()
    else:
        print(__doc__)
